(() => {
'use strict';
const $=id=>document.getElementById(id), SAVE='arcane-salvage.phaser.v1';
const cards={bolt:['奥术电弧',1,'attack','攻击','造成 7 点伤害。'],guard:['符文壁垒',1,'skill','护盾','获得 7 点护盾。'],spark:['拾荒火花',0,'tech','拾荒','抽 1 张牌；下一次攻击 +2。'],capacitor:['咒能电容',2,'tech','易变','造成 5 点伤害，获得 1 能量。'],siphon:['以太虹吸',2,'skill','仪式','造成 4 点伤害，恢复 4 点生命。'],barrage:['碎片齐射',1,'attack','攻击','造成 5 点伤害两次。'],ward:['偏折阵列',1,'skill','护盾','获得 5 点护盾，抽 1 张牌。'],overload:['过载符文',3,'tech','易变','造成 18 点伤害。']};
const nodes={start:{name:'坍塌之门',kind:'起点',next:['patrol','workshop']},patrol:{name:'巡逻熔炉',kind:'战斗',enemy:'patrol',next:['elite']},workshop:{name:'修补工坊',kind:'工坊',next:['anomaly']},elite:{name:'虚无祭司地窖',kind:'精英',enemy:'elite',next:['cache']},anomaly:{name:'低语发电机',kind:'异常',next:['bridge']},cache:{name:'封印圣匣',kind:'圣匣',next:['boss']},bridge:{name:'导管桥',kind:'战斗',enemy:'bridge',next:['boss']},boss:{name:'大工匠',kind:'首领',enemy:'boss',next:[]}};
const foes={patrol:['铜壳巡逻者',42,18,[['粉碎打击',7],['黄铜镀层',-6],['沉降重击',10]]],elite:['虚无祭司',62,32,[['虚无脉冲',6],['祭仪壁垒',-10],['湮灭祷言',14]]],bridge:['导管巨像',58,28,[['电弧横扫',9],['导管充能',-8],['超载坠击',15]]],boss:['大工匠',88,60,[['锻炉火花',8],['完美装甲',-12],['拆解光束',18]] ]};
function fresh(){return {hp:52,max:52,block:0,scrap:0,deck:['bolt','bolt','guard','guard','spark','spark','capacitor','capacitor','siphon','siphon'],draw:[],hand:[],discard:[],energy:0,boost:0,current:'start',done:['start'],mode:'map',enemy:null,enemyId:null,intent:0,turn:0,relic:'',reward:[],logs:['你抵达坍塌之门。选择一处相邻地点。']};}
function validCards(a){return Array.isArray(a)&&a.every(id=>cards[id]);}function load(){try{let v=JSON.parse(localStorage.getItem(SAVE));if(!v)return fresh();let modes=['map','combat','reward','won','dead'];if(!nodes[v.current]||!modes.includes(v.mode)||!validCards(v.deck)||!validCards(v.draw)||!validCards(v.hand)||!validCards(v.discard)||!validCards(v.reward)||!Array.isArray(v.done)||!Array.isArray(v.logs)||!Number.isFinite(v.hp)||!Number.isFinite(v.max)||!Number.isFinite(v.scrap)||!Number.isFinite(v.energy)||!Number.isFinite(v.block)||!Number.isFinite(v.boost))throw 0;if(v.mode==='combat'&&(!foes[v.enemyId]||!v.enemy||!Number.isFinite(v.enemy.hp)||!Number.isFinite(v.enemy.max)||!Number.isFinite(v.enemy.block)||!Number.isInteger(v.intent)||!foes[v.enemyId][3][v.intent]))throw 0;return v;}catch{try{localStorage.removeItem(SAVE)}catch{}return fresh();}}let s=load();
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a}function say(t){s.logs.push(t);s.logs=s.logs.slice(-40);$('live').textContent=t}function draw(n){while(n--){if(!s.draw.length&&s.discard.length){s.draw=shuffle(s.discard.splice(0));say('弃牌堆洗入抽牌堆。')}if(s.draw.length)s.hand.push(s.draw.pop())}}
function hurt(target,n){let b=Math.min(target.block,n);target.block-=b;target.hp=Math.max(0,target.hp-(n-b));return n-b}function hit(n,attack=true){let d=hurt(s.enemy,n+(attack?s.boost:0));if(attack)s.boost=0;say(`造成 ${d} 点伤害。`)}
function begin(id){s.current=id;let f=foes[nodes[id].enemy];s.mode='combat';s.enemy={name:f[0],hp:f[1],max:f[1],block:0,reward:f[2]};s.enemyId=nodes[id].enemy;s.intent=0;s.turn=1;s.energy=3;s.boost=0;s.draw=shuffle([...s.deck]);s.hand=[];s.discard=[];draw(5);say(`遭遇 ${f[0]}，第 1 回合开始。`)}
function choose(id){if(s.mode!=='map'||!nodes[s.current].next.includes(id))return;let n=nodes[id];if(n.enemy){begin(id);render();return;}s.current=id;s.done.push(id);if(id==='workshop'){let attack=s.deck.find(x=>cards[x][2]==='attack')||'bolt';s.deck.push(attack);say(`工坊复制了「${cards[attack][0]}」。`)}if(id==='anomaly'){s.hp=Math.min(s.max,s.hp+8);s.scrap+=12;say('以太灌注：恢复 8 生命，获得 12 零件。')}if(id==='cache'){s.hp=Math.min(s.max,s.hp+10);s.scrap+=16;say('封印圣匣：恢复 10 生命，获得 16 零件。')}render()}
function win(){s.scrap+=s.enemy.reward;s.done.push(s.current);say(`胜利！获得 ${s.enemy.reward} 零件。`);if(s.current==='elite'){s.relic='回响棱镜';s.max+=5;s.hp+=5;say('遗物「回响棱镜」：最大生命 +5。')}if(s.current==='boss'){s.mode='won';s.reward=[];say('远征完成！大工匠已被拆解。')}else{s.mode='reward';s.reward=s.current==='bridge'?['barrage','ward','overload']:['barrage','ward','spark'];} }
function play(i){if(s.mode!=='combat')return;let id=s.hand[i],c=cards[id];if(!c||s.energy<c[1])return;s.energy-=c[1];s.hand.splice(i,1);s.discard.push(id);say(`使用「${c[0]}」。`);if(id==='bolt')hit(7);if(id==='guard'){s.block+=7;say('获得 7 护盾。')}if(id==='spark'){s.boost+=2;draw(1)}if(id==='capacitor'){hit(5,false);s.energy++}if(id==='siphon'){hit(4,false);s.hp=Math.min(s.max,s.hp+4)}if(id==='barrage'){hit(5);if(s.enemy.hp>0)hit(5)}if(id==='ward'){s.block+=5;draw(1)}if(id==='overload')hit(18);if(s.enemy.hp<=0)win();render()}
function end(){if(s.mode!=='combat')return;s.discard.push(...s.hand.splice(0));let it=foes[s.enemyId][3][s.intent];if(it[1]<0){s.enemy.block+=-it[1];say(`${s.enemy.name} 使用 ${it[0]}，获得 ${-it[1]} 护甲。`)}else{let d=hurt({get hp(){return s.hp},set hp(v){s.hp=v},get block(){return s.block},set block(v){s.block=v}},it[1]);say(`${s.enemy.name} 使用 ${it[0]}，造成 ${d} 点伤害。`)}if(s.hp<=0){s.mode='dead';say('远征失败。重开以再次尝试。');return render()}s.enemy.block=0;s.block=0;s.intent=(s.intent+1)%3;s.turn++;s.energy=3;s.boost=0;draw(5);say(`第 ${s.turn} 回合：抽取 ${s.hand.length} 张手牌。`);render()}
function render(){try{localStorage.setItem(SAVE,JSON.stringify(s));}catch{}$('hp').textContent=`${s.hp} / ${s.max}`;$('scrap').textContent=s.scrap;$('deck').textContent=`${s.deck.length} 张`;$('relic').textContent=s.relic||'无';let combat=s.mode==='combat', n=nodes[s.current];$('title').textContent=combat?`${s.enemy.name} · 第 ${s.turn} 回合`:s.mode==='won'?'远征完成':s.mode==='dead'?'远征失败':n.name;$('summary').textContent=combat?`敌方意图：${foes[s.enemyId][3][s.intent][0]} · 敌人 ${s.enemy.hp}/${s.enemy.max}${s.enemy.block?'，护甲 '+s.enemy.block:''} · 你有 ${s.block} 护盾 / ${s.energy} 能量`:(s.mode==='map'?`${n.kind}：选择金色的相邻地点。`:'选择战利品，或跳过。');$('end').disabled=!combat;$('repair').disabled=s.mode!=='map'||s.scrap<15||s.hp>=s.max;$('hand').replaceChildren(...(combat?s.hand.map((id,i)=>{let c=cards[id],b=document.createElement('button');b.className='card '+c[2];b.disabled=s.energy<c[1];b.innerHTML=`<span class="cost">${c[1]}</span><span class="type">${c[3]}</span><h3>${c[0]}</h3><p>${c[4]}</p>`;b.onclick=()=>play(i);return b}):[]));if(!combat)$('hand').textContent='Phaser 战场会随路线和战斗状态变化；所有操作均由此处的无障碍按钮完成。';let ns=$('nodes');ns.replaceChildren(...Object.entries(nodes).map(([id,x])=>{let b=document.createElement('button');let ok=s.mode==='map'&&nodes[s.current].next.includes(id);b.className='node '+(ok?'reachable ':'')+(s.done.includes(id)?'completed':'');b.textContent=`${x.kind} · ${x.name}`;b.disabled=!ok;b.onclick=()=>choose(id);return b}));$('log').replaceChildren(...s.logs.map(x=>{let li=document.createElement('li');li.textContent=x;return li}));$('log').scrollTop=99999;let r=$('reward'),show=s.mode==='reward'||s.mode==='won';r.classList.toggle('show',show);$('rewardTitle').textContent=s.mode==='won'?'秘法已回收':'战斗战利品';$('rewardText').textContent=s.mode==='won'?'你穿过了以太工坊。':'选择一张卡加入卡组。';$('choices').replaceChildren(...s.reward.map(id=>{let b=document.createElement('button');b.className='action';b.textContent=`${cards[id][0]} · ${cards[id][4]}`;b.onclick=()=>{s.deck.push(id);say(`获得「${cards[id][0]}」。`);closeReward()};return b}));$('skip').textContent=s.mode==='won'?'开始新的远征':'跳过，继续远征';paint();}
function closeReward(){s.mode='map';s.enemy=null;s.enemyId=null;s.reward=[];render()}$('end').onclick=end;$('skip').onclick=()=>s.mode==='won'?reset():closeReward();$('repair').onclick=()=>{if(s.scrap>=15&&s.mode==='map'){s.scrap-=15;s.hp=Math.min(s.max,s.hp+10);say('现场修复恢复 10 生命。');render()}};function reset(){s=fresh();localStorage.removeItem(SAVE);render()}$('newRun').onclick=reset;
const MAP_IDS=['start','patrol','workshop','elite','anomaly','cache','bridge','boss'],MAP_POINTS=[[.12,.78],[.3,.57],[.31,.83],[.5,.38],[.52,.67],[.72,.23],[.72,.52],[.9,.12]];let scene={create(){this.g=this.add.graphics();this.t=this.add.text(24,20,'',{fontFamily:'Georgia, serif',fontSize:'22px',color:'#dffcff'});this.input.on('pointerdown',pointer=>{if(s.mode!=='map')return;let w=this.scale.width,h=this.scale.height,hit=Math.max(42,Math.min(w,h)*.12);for(let i=0;i<MAP_IDS.length;i++){let p=MAP_POINTS[i],dx=pointer.x-w*p[0],dy=pointer.y-h*p[1];if(dx*dx+dy*dy<=hit*hit){choose(MAP_IDS[i]);return;}}});this.time.addEvent({delay:180,loop:true,callback:paint})}};let game=new Phaser.Game({type:Phaser.AUTO,parent:'stage',backgroundColor:'#091321',scene,scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%',autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true}});function paint(){if(!game.scene||!game.scene.keys.default)return;let sc=game.scene.keys.default,g=sc.g,w=game.scale.width,h=game.scale.height;if(!g)return;g.clear();for(let x=0;x<w;x+=42)g.lineStyle(1,0x183147,.38).lineBetween(x,0,x,h);for(let y=0;y<h;y+=42)g.lineStyle(1,0x183147,.38).lineBetween(0,y,w,y);let combat=s.mode==='combat';if(combat){g.fillStyle(0x143344,.9).fillCircle(w*.23,h*.54,Math.min(w,h)*.17);g.fillStyle(0x4c2639,.9).fillCircle(w*.77,h*.54,Math.min(w,h)*.18);g.lineStyle(3,0x64e8dd,.5).strokeCircle(w*.23,h*.54,Math.min(w,h)*.2);g.lineStyle(3,0xff7482,.5).strokeCircle(w*.77,h*.54,Math.min(w,h)*.21);sc.t.setText(`玛拉 · ${s.hp}/${s.max}     ◈     ${s.enemy.name} · ${s.enemy.hp}/${s.enemy.max}`)}else{let pts=[[.12,.78],[.3,.57],[.31,.83],[.5,.38],[.52,.67],[.72,.23],[.72,.52],[.9,.12]];let ids=['start','patrol','workshop','elite','anomaly','cache','bridge','boss'];g.lineStyle(2,0x557287,.6);[[0,1],[0,2],[1,3],[2,4],[3,5],[4,6],[5,7],[6,7]].forEach(e=>g.lineBetween(w*pts[e[0]][0],h*pts[e[0]][1],w*pts[e[1]][0],h*pts[e[1]][1]));ids.forEach((id,i)=>{let ok=s.mode==='map'&&nodes[s.current].next.includes(id), done=s.done.includes(id);g.fillStyle(ok?0xf0bf61:done?0x64e8dd:0x253d54).fillCircle(w*pts[i][0],h*pts[i][1],18);g.lineStyle(2,0xffffff,.45).strokeCircle(w*pts[i][0],h*pts[i][1],18)});sc.t.setText(`第一区 · ${nodes[s.current].name} · ${s.mode==='won'?'远征完成':'规划路线'}`)}}
render();
})();
